student_list:
  path: /
  controller: app\controllers\SiteController
  function: list

student_update:
  path: /update
  controller: app\controllers\SiteController
  function: update

student_save:
  path: /save
  controller: app\controllers\SiteController
  function: save

student_delete:
  method: get
  path: /delete
  controller: app\controllers\SiteController
  function: delete