#name:
#   method:
#   controller:
#//  $app->router->get('/', [SiteController::class, 'list']);
#//  $app->router->post('/', [SiteController::class, 'list']);
#//  $app->router->get('/update', [SiteController::class, 'update']);
#//  $app->router->post('/update', [SiteController::class, 'update']);
#//  $app->router->get('/save', [SiteController::class, 'save']);
#//  $app->router->post('/save', [SiteController::class, 'save']);
#//  $app->router->get('/delete', [SiteController::class, 'delete']);
student_list:
  path: /
  controller: app\controllers\SiteController
  function: list

student_update:
  path: /update
  controller: app\controllers\SiteController
  function: update

student_save:
  path: /save
  controller: app\controllers\SiteController
  function: save

student_delete:
  method: get
  path: /delete
  controller: app\controllers\SiteController
  function: delete